### ISSUE TITLE
Write an optional template for new workshops

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Workshops#77]
Much like https://github.com/CodeYourFuture/CYF-Coursework-Template/blob/main/README.md

Also optionally, any extra front matter you might want in comments eg 

```
<!--
+++
title=""
time=30
facilitation=true
[objectives]
1="Use the [Teach Tech Together](https://teachtogether.tech/en/index.html#s:process-objectives) guide to construct your objectives"
2="Limit the objectives to 3-5 items"
3="Write objectives you can measure"
+++
-->
```

**Comment by SallyMcGrath** [comment]
PS rn this entire repo is a public template - should it be?

**Comment by Dedekind561** [comment]
Workshop template was added a while back - thankyou! I'm spring cleaning atm 🧹
